# Python to help generate the sed script map
# Based on HAnim 1.1 and HAnim 2.0 naming conventions
# This map tries to cover standard joints.
# If your V1 files use non-standard names, you'll need to add them.

joint_map_list = [
("chin", "menton"),
("humanoid_root", "humanoid_root"),
("HumanoidRoot", "humanoid_root"),
("SIJ", "sacroiliac"),
("SI joint", "sacroiliac"),
("l_hip", "l_hip"),
("l_knee", "l_knee"),
("l_ankle", "l_talocrural"),
("l_talocalcaneal", "l_talocalcaneonavicular"),
("l_cuneonavicular_1", "l_cuneonavicular_1"),
("l_tarsometatarsal_1", "l_tarsometatarsal_1"),
("l_metatarsophalangeal_1", "l_metatarsophalangeal_1"),
("l_tarsal_interphalangeal_1", "l_tarsal_interphalangeal_1"),
("l_cuneonavicular", "l_cuneonavicular_2"),
("l_subtalar", "l_tarsometatarsal_2"),
("l_tarsometatarsal", "l_tarsometatarsal_2"),
("l_midtarsal", "l_metatarsophalangeal_2"),
("l_metatarsophalangeal", "l_metatarsophalangeal_2"),
("l_tarsal_proximal_interphalangeal", "l_tarsal_proximal_interphalangeal_2"),
("l_tarsal_distal_interphalangeal", "l_tarsal_distal_interphalangeal_2"),
("l_cuneonavicular_3", "l_cuneonavicular_3"),
("l_tarsometatarsal_3", "l_tarsometatarsal_3"),
("l_metatarsophalangeal_3", "l_metatarsophalangeal_3"),
("l_tarsal_proximal_interphalangeal_3", "l_tarsal_proximal_interphalangeal_3"),
("l_tarsal_distal_interphalangeal_3", "l_tarsal_distal_interphalangeal_3"),
("l_calcaneuscuboid", "l_calcaneocuboid"),
("l_transversetarsal", "l_transversetarsal"),
("l_tarsometatarsal_4", "l_tarsometatarsal_4"),
("l_metatarsophalangeal_4", "l_metatarsophalangeal_4"),
("l_tarsal_proximal_interphalangeal_4", "l_tarsal_proximal_interphalangeal_4"),
("l_tarsal_distal_interphalangeal_4", "l_tarsal_distal_interphalangeal_4"),
("l_tarsometatarsal_5", "l_tarsometatarsal_5"),
("l_metatarsophalangeal_5", "l_metatarsophalangeal_5"),
("l_tarsal_proximal_interphalangeal_5", "l_tarsal_proximal_interphalangeal_5"),
("l_tarsal_distal_interphalangeal_5", "l_tarsal_distal_interphalangeal_5"),
("r_hip", "r_hip"),
("r_knee", "r_knee"),
("r_ankle", "r_talocrural"),
("r_talocalcaneal", "r_talocalcaneonavicular"),
("r_cuneonavicular_1", "r_cuneonavicular_1"),
("r_tarsometatarsal_1", "r_tarsometatarsal_1"),
("r_metatarsophalangeal_1", "r_metatarsophalangeal_1"),
("r_tarsal_interphalangeal_1", "r_tarsal_interphalangeal_1"),
("r_cuneonavicular", "r_cuneonavicular_2"),
("r_subtalar", "r_tarsometatarsal_2"),
("r_tarsometatarsal", "r_tarsometatarsal_2"),
("r_midtarsal", "r_metatarsophalangeal_2"),
("r_metatarsophalangeal", "r_metatarsophalangeal_2"),
("r_tarsal_proximal_interphalangeal", "r_tarsal_proximal_interphalangeal_2"),
("r_metatarsal", "r_tarsal_distal_interphalangeal_2"),
("r_tarsal_distal_interphalangeal", "r_tarsal_distal_interphalangeal_2"),
("r_cuneonavicular_3", "r_cuneonavicular_3"),
("r_tarsometatarsal_3", "r_tarsometatarsal_3"),
("r_metatarsophalangeal_3", "r_metatarsophalangeal_3"),
("r_tarsal_proximal_interphalangeal_3", "r_tarsal_proximal_interphalangeal_3"),
("r_tarsal_distal_interphalangeal_3", "r_tarsal_distal_interphalangeal_3"),
("r_calcaneuscuboid", "r_calcaneocuboid"),
("r_transversetarsal", "r_transversetarsal"),
("r_tarsometatarsal_4", "r_tarsometatarsal_4"),
("r_metatarsophalangeal_4", "r_metatarsophalangeal_4"),
("r_tarsal_proximal_interphalangeal_4", "r_tarsal_proximal_interphalangeal_4"),
("r_tarsal_distal_interphalangeal_4", "r_tarsal_distal_interphalangeal_4"),
("r_tarsometatarsal_5", "r_tarsometatarsal_5"),
("r_metatarsophalangeal_5", "r_metatarsophalangeal_5"),
("r_tarsal_proximal_interphalangeal_5", "r_tarsal_proximal_interphalangeal_5"),
("r_tarsal_distal_interphalangeal_5", "r_tarsal_distal_interphalangeal_5"),
("vl5", "vl5"),
("vl4", "vl4"),
("vl3", "vl3"),
("vl2", "vl2"),
("vl1", "vl1"),
("vt12", "vt12"),
("vt11", "vt11"),
("vt10", "vt10"),
("vt9", "vt9"),
("vt8", "vt8"),
("vt7", "vt7"),
("vt6", "vt6"),
("vt5", "vt5"),
("vt4", "vt4"),
("vt3", "vt3"),
("vt2", "vt2"),
("vt1", "vt1"),
("vc7", "vc7"),
("vc6", "vc6"),
("vc5", "vc5"),
("vc4", "vc4"),
("vc3", "vc3"),
("vc2", "vc2"),
("vc1", "vc1"),
("skullbase", "skullbase"),
("l_eyelid_joint", "l_eyelid_joint"),
("r_eyelid_joint", "r_eyelid_joint"),
("l_eyeball_joint", "l_eyeball_joint"),
("r_eyeball_joint", "r_eyeball_joint"),
("l_eyebrow_joint", "l_eyebrow_joint"),
("r_eyebrow_joint", "r_eyebrow_joint"),
("temporomandibular", "temporomandibular"),
("l_sternoclavicular", "l_sternoclavicular"),
("l_acromioclavicular", "l_acromioclavicular"),
("l_shoulder", "l_shoulder"),
("l_elbow", "l_elbow"),
("l_wrist", "l_radiocarpal"),
("l_midcarpal_1", "l_midcarpal_1"),
("l_thumb1", "l_carpometacarpal_1"),
("l_thumb2", "l_metacarpophalangeal_1"),
("l_thumb3", "l_carpal_interphalangeal_1"),
("l_midcarpal_2", "l_midcarpal_2"),
("l_index0", "l_carpometacarpal_2"),
("l_carpometacarpal", "l_carpometacarpal_2"),
("l_index1", "l_metacarpophalangeal_2"),
("l_metacarpophalangeal", "l_metacarpophalangeal_2"),
("l_index2", "l_carpal_proximal_interphalangeal_2"),
("l_carpal_proximal_interphalangeal", "l_carpal_proximal_interphalangeal_2"),
("l_index3", "l_carpal_distal_interphalangeal_2"),
("l_carpal_distal_interphalangeal", "l_carpal_distal_interphalangeal_2"),
("l_midcarpal_3", "l_midcarpal_3"),
("l_middle0", "l_carpometacarpal_3"),
("l_middle1", "l_metacarpophalangeal_3"),
("l_middle2", "l_carpal_proximal_interphalangeal_3"),
("l_middle3", "l_carpal_distal_interphalangeal_3"),
("l_midcarpal_4_5", "l_midcarpal_4_5"),
("l_ring0", "l_carpometacarpal_4"),
("l_ring1", "l_metacarpophalangeal_4"),
("l_ring2", "l_carpal_proximal_interphalangeal_4"),
("l_ring3", "l_carpal_distal_interphalangeal_4"),
("l_pinky0", "l_carpometacarpal_5"),
("l_pinky1", "l_metacarpophalangeal_5"),
("l_pinky2", "l_carpal_proximal_interphalangeal_5"),
("l_pinky3", "l_carpal_distal_interphalangeal_5"),
("r_sternoclavicular", "r_sternoclavicular"),
("r_acromioclavicular", "r_acromioclavicular"),
("r_shoulder", "r_shoulder"),
("r_elbow", "r_elbow"),
("r_wrist", "r_radiocarpal"),
("r_midcarpal_1", "r_midcarpal_1"),
("r_thumb1", "r_carpometacarpal_1"),
("r_thumb2", "r_metacarpophalangeal_1"),
("r_thumb3", "r_carpal_interphalangeal_1"),
("r_midcarpal_2", "r_midcarpal_2"),
("r_index0", "r_carpometacarpal_2"),
("r_carpometacarpal", "r_carpometacarpal_2"),
("r_index1", "r_metacarpophalangeal_2"),
("r_metacarpophalangeal", "r_metacarpophalangeal_2"),
("r_index2", "r_carpal_proximal_interphalangeal_2"),
("r_carpal_proximal_interphalangeal", "r_carpal_proximal_interphalangeal_2"),
("r_index3", "r_carpal_distal_interphalangeal_2"),
("r_carpal_distal_interphalangeal", "r_carpal_distal_interphalangeal_2"),
("r_midcarpal_3", "r_midcarpal_3"),
("r_middle0", "r_carpometacarpal_3"),
("r_middle1", "r_metacarpophalangeal_3"),
("r_middle2", "r_carpal_proximal_interphalangeal_3"),
("r_middle3", "r_carpal_distal_interphalangeal_3"),
("r_midcarpal_4_5", "r_midcarpal_4_5"),
("r_ring0", "r_carpometacarpal_4"),
("r_ring1", "r_metacarpophalangeal_4"),
("r_ring2", "r_carpal_proximal_interphalangeal_4"),
("r_ring3", "r_carpal_distal_interphalangeal_4"),
("r_pinky0", "r_carpometacarpal_5"),
("r_pinky1", "r_metacarpophalangeal_5"),
("r_pinky2", "r_carpal_proximal_interphalangeal_5"),
("r_pinky3", "r_carpal_distal_interphalangeal_5"),
("skull_tip", "skull_vertex"),
("vertex", "skull_vertex"),
("glabella", "glabella"),
("sellion", "sellion"),
("l_infraorbitale", "l_infraorbitale"),
("l_tragion", "l_tragion"),
("l_gonion", "l_gonion"),
("r_infraorbitale", "r_infraorbitale"),
("r_tragion", "r_tragion"),
("r_gonion", "r_gonion"),
("supramenton", "supramenton"),
("cervicale", "cervicale"),
("adams_apple", "adams_apple"),
("suprasternale", "suprasternale"),
("substernale", "substernale"),
("l_clavicale", "l_clavicle"),
("l_acromion", "l_acromion"),
("l_axilla_ant", "l_axilla_proximal"),
("l_axilla_post", "l_axilla_distal"),
("l_axilla_posterior_folds", "l_axilla_posterior_folds"),
("r_clavicale", "r_clavicle"),
("r_acromion", "r_acromion"),
("r_axilla_ant", "r_axilla_proximal"),
("r_axilla_post", "r_axilla_distal"),
("r_axilla_posterior_folds", "r_axilla_posterior_folds"),
("middle back", "spine_1_middle_back"),
("lower back", "spine_2_lower_back"),
("waist_preferred_ant", "waist_preferred_anterior"),
("waist_preferred_post", "waist_preferred_posterior"),
("l_rib10_midspine", "l_rib10"),
("Left Bustpoint", "l_thelion"),
("r_rib10_midspine", "r_rib10"),
("Right Bustpoint", "r_thelion"),
("Left Anterior Superior Iliac Spine", "l_asis"),
("l_iliocristale", "l_iliocristale"),
("Left Posterior Superior Iliac Spine", "l_psis"),
("Right Anterior Superior Iliac Spine", "r_asis"),
("r_iliocristale", "r_iliocristale"),
("Right Posterior Superior Iliac Spine", "r_psis"),
("crotch", "crotch"),
("l_femoral_lateral_epicn", "l_femoral_lateral_epicondyle"),
("l_femoral_lateral_epicondyles", "l_femoral_lateral_epicondyle"),
("l_femoral_medial_epicn", "l_femoral_medial_epicondyle"),
("l_femoral_medial_epicondyles", "l_femoral_medial_epicondyle"),
("l_kneecap", "l_suprapatella"),
("l_trochanter", "l_trochanterion"),
("r_femoral_lateral_epicn", "r_femoral_lateral_epicondyle"),
("r_femoral_lateral_epicondyles", "r_femoral_lateral_epicondyle"),
("r_femoral_medial_epicn", "r_femoral_medial_epicondyle"),
("r_femoral_medial_epicondyles", "r_femoral_medial_epicondyle"),
("r_kneecap", "r_suprapatella"),
("r_trochanter", "r_trochanterion"),
("l_tibiale", "l_tibiale"),
("l_medial_malleolus", "l_medial_malleolus"),
("l_lateral_malleolus", "l_lateral_malleolus"),
("l_sphyrion", "l_sphyrion"),
("r_tibiale", "r_tibiale"),
("r_medial_malleolus", "r_medial_malleolus"),
("r_lateral_malleolus", "r_lateral_malleolus"),
("r_sphyrion", "r_sphyrion"),
("l_metatarsal_pha1", "l_metatarsal_phalanx_1"),
("l_metatarsal_pha5", "l_metatarsal_phalanx_5"),
("l_dactylion", "l_dactylion"),
("l_calcaneous_post", "l_calcaneus_posterior"),
("r_metatarsal_pha1", "r_metatarsal_phalanx_1"),
("r_metatarsal_pha5", "r_metatarsal_phalanx_5"),
("r_dactylion", "r_dactylion"),
("r_calcaneous_post", "r_calcaneus_posterior"),
("l_humeral_lateral_epicn", "l_humeral_lateral_epicondyle"),
("l_humeral_lateral_epicondyles", "l_humeral_lateral_epicondyle"),
("l_humeral_medial_epicn", "l_humeral_medial_epicondyle"),
("l_humeral_medial_epicondyles", "l_humeral_medial_epicondyle"),
("l_olecranon", "l_olecranon"),
("r_humeral_lateral_epicn", "r_humeral_lateral_epicondyle"),
("r_humeral_lateral_epicondyles", "r_humeral_lateral_epicondyle"),
("r_humeral_medial_epicn", "r_humeral_medial_epicondyle"),
("r_humeral_medial_epicondyles", "r_humeral_medial_epicondyle"),
("r_olecranon", "r_olecranon"),
("l_radiale", "l_radiale"),
("l_ulnar_styloid", "l_ulnar_styloid"),
("l_radial_styloid", "l_radial_styloid"),
("r_radiale", "r_radiale"),
("r_ulnar_styloid", "r_ulnar_styloid"),
("r_radial_styloid", "r_radial_styloid"),
("l_metacarpal_pha2", "l_metacarpal_phalanx_2"),
("l_metacarpal_phalanx", "l_metacarpal_phalanx_2"),
("l_metacarpal_phalanx_3", "l_metacarpal_phalanx_3"),
("l_metacarpal_pha5", "l_metacarpal_phalanx_5"),
("r_metacarpal_pha2", "r_metacarpal_phalanx_2"),
("r_metacarpal_phalanx", "r_metacarpal_phalanx_2"),
("r_metacarpal_phalanx_3", "r_metacarpal_phalanx_3"),
("r_metacarpal_pha5", "r_metacarpal_phalanx_5"),
("nuchal", "nuchale"),
("l_neck_base", "l_neck_base"),
("r_neck_base", "r_neck_base"),
("belly button", "navel"),
("l_canthus", "l_ectocanthus"),
("r_canthus", "r_ectocanthus"),
("mesosternum", "mesosternale"),
("opisthocranion", "opisthocranion"),
("l_knee_crease", "l_knee_crease"),
("r_knee_crease", "r_knee_crease"),
("median plane", "rear_center_midsagittal_plane"),
("buttocks_standing_wall_contact_point", "buttocks_standing_wall_contact_point"),
("l_chest_midsagittal_plane", "l_chest_midsagittal_plane"),
("r_chest_midsagittal_plane", "r_chest_midsagittal_plane"),
("l_bideltoid", "l_bideltoid"),
("r_bideltoid", "r_bideltoid"),
("l_thumb_distal", "l_carpal_distal_phalanx_1"),
("l_index_distal", "l_carpal_distal_phalanx_2"),
("l_middle_distal", "l_carpal_distal_phalanx_3"),
("l_ring_distal", "l_carpal_distal_phalanx_4"),
("l_pinky_distal", "l_carpal_distal_phalanx_5"),
("r_thumb_distal", "r_carpal_distal_phalanx_1"),
("r_index_distal", "r_carpal_distal_phalanx_2"),
("r_middle_distal", "r_carpal_distal_phalanx_3"),
("r_ring_distal", "r_carpal_distal_phalanx_4"),
("r_pinky_distal", "r_carpal_distal_phalanx_5"),
("l_tarsal_distal_phalanx_1", "l_tarsal_distal_phalanx_1"),
("l_digit2", "l_tarsal_distal_phalanx_2"),
("l_tarsal_distal_phalanx_3", "l_tarsal_distal_phalanx_3"),
("l_tarsal_distal_phalanx_4", "l_tarsal_distal_phalanx_4"),
("l_tarsal_distal_pha5", "l_tarsal_distal_phalanx_5"),
("r_tarsal_distal_phalanx_1", "r_tarsal_distal_phalanx_1"),
("r_digit2", "r_tarsal_distal_phalanx_2"),
("r_tarsal_distal_phalanx_3", "r_tarsal_distal_phalanx_3"),
("r_tarsal_distal_phalanx_4", "r_tarsal_distal_phalanx_4"),
("r_tarsal_distal_pha5", "r_tarsal_distal_phalanx_5"),
("sacrum", "sacrum"),
("pelvis", "pelvis"),
("l_thigh", "l_thigh"),
("l_calf", "l_calf"),
("l_hindfoot", "l_talus"),
("l_navicular", "l_navicular"),
("l_cuneiform_1", "l_cuneiform_1"),
("l_metatarsal_1", "l_metatarsal_1"),
("l_tarsal_proximal_phalanx_1", "l_tarsal_proximal_phalanx_1"),
("l_tarsal_distal_phalanx_1", "l_tarsal_distal_phalanx_1"),
("l_cuneiform", "l_cuneiform_2"),
("l_midproximal", "l_metatarsal_2"),
("l_metatarsal", "l_metatarsal_2"),
("l_middistal", "l_tarsal_proximal_phalanx_2"),
("l_tarsal_proximal_phalanx", "l_tarsal_proximal_phalanx_2"),
("l_tarsal_middle_phalanx", "l_tarsal_middle_phalanx_2"),
("l_forefoot", "l_tarsal_distal_phalanx_2"),
("l_tarsal_distal_phalanx", "l_tarsal_distal_phalanx_2"),
("l_cuneiform_3", "l_cuneiform_3"),
("l_metatarsal_3", "l_metatarsal_3"),
("l_tarsal_proximal_phalanx_3", "l_tarsal_proximal_phalanx_3"),
("l_tarsal_middle_phalanx_3", "l_tarsal_middle_phalanx_3"),
("l_tarsal_distal_phalanx_3", "l_tarsal_distal_phalanx_3"),
("l_calcaneum", "l_calcaneus"),
("l_cuboid", "l_cuboid"),
("l_metatarsal_4", "l_metatarsal_4"),
("l_tarsal_proximal_phalanx_4", "l_tarsal_proximal_phalanx_4"),
("l_tarsal_middle_phalanx_4", "l_tarsal_middle_phalanx_4"),
("l_tarsal_distal_phalanx_4", "l_tarsal_distal_phalanx_4"),
("l_metatarsal_5", "l_metatarsal_5"),
("l_tarsal_proximal_phalanx_5", "l_tarsal_proximal_phalanx_5"),
("l_tarsal_middle_phalanx_5", "l_tarsal_middle_phalanx_5"),
("l_tarsal_distal_phalanx_5", "l_tarsal_distal_phalanx_5"),
("r_thigh", "r_thigh"),
("r_calf", "r_calf"),
("r_hindfoot", "r_talus"),
("r_navicular", "r_navicular"),
("r_cuneiform_1", "r_cuneiform_1"),
("r_metatarsal_1", "r_metatarsal_1"),
("r_tarsal_proximal_phalanx_1", "r_tarsal_proximal_phalanx_1"),
("r_tarsal_distal_phalanx_1", "r_tarsal_distal_phalanx_1"),
("r_cuneiform", "r_cuneiform_2"),
("r_midproximal", "r_metatarsal_2"),
("r_middistal", "r_tarsal_proximal_phalanx_2"),
("r_tarsal_proximal_phalanx", "r_tarsal_proximal_phalanx_2"),
("r_tarsal_middle_phalanx", "r_tarsal_middle_phalanx_2"),
("r_forefoot", "r_tarsal_distal_phalanx_2"),
("r_tarsal_distal_phalanx", "r_tarsal_distal_phalanx_2"),
("r_cuneiform_3", "r_cuneiform_3"),
("r_metatarsal_3", "r_metatarsal_3"),
("r_tarsal_proximal_phalanx_3", "r_tarsal_proximal_phalanx_3"),
("r_tarsal_middle_phalanx_3", "r_tarsal_middle_phalanx_3"),
("r_tarsal_distal_phalanx_3", "r_tarsal_distal_phalanx_3"),
("r_calcaneum", "r_calcaneus"),
("r_cuboid", "r_cuboid"),
("r_metatarsal_4", "r_metatarsal_4"),
("r_tarsal_proximal_phalanx_4", "r_tarsal_proximal_phalanx_4"),
("r_tarsal_middle_phalanx_4", "r_tarsal_middle_phalanx_4"),
("r_tarsal_distal_phalanx_4", "r_tarsal_distal_phalanx_4"),
("r_metatarsal_5", "r_metatarsal_5"),
("r_tarsal_proximal_phalanx_5", "r_tarsal_proximal_phalanx_5"),
("r_tarsal_middle_phalanx_5", "r_tarsal_middle_phalanx_5"),
("r_tarsal_distal_phalanx_5", "r_tarsal_distal_phalanx_5"),
("l5", "l5"),
("l4", "l4"),
("l3", "l3"),
("l2", "l2"),
("l1", "l1"),
("t12", "t12"),
("t11", "t11"),
("t10", "t10"),
("t9", "t9"),
("t8", "t8"),
("t7", "t7"),
("t6", "t6"),
("t5", "t5"),
("t4", "t4"),
("t3", "t3"),
("t2", "t2"),
("t1", "t1"),
("c7", "c7"),
("c6", "c6"),
("c5", "c5"),
("c4", "c4"),
("c3", "c3"),
("c2", "c2"),
("c1", "c1"),
("head", "skull"),
("l_eyelid", "l_eyelid"),
("r_eyelid", "r_eyelid"),
("l_eyeball", "l_eyeball"),
("r_eyeball", "r_eyeball"),
("l_eyebrow", "l_eyebrow"),
("r_eyebrow", "r_eyebrow"),
("jaw", "jaw"),
("l_clavicle", "l_clavicle"),
("l_scapula", "l_scapula"),
("l_upperarm", "l_upperarm"),
("l_forearm", "l_forearm"),
("l_trapezium", "l_trapezium"),
("l_thumb_metacarpal", "l_metacarpal_1"),
("l_thumb_proximal", "l_carpal_proximal_phalanx_1"),
("l_thumb_distal", "l_carpal_distal_phalanx_1"),
("l_trapezoid", "l_trapezoid"),
("l_index_metacarpal", "l_metacarpal_2"),
("l_index_proximal", "l_carpal_proximal_phalanx_2"),
("l_carpal_proximal_phalanx", "l_carpal_proximal_phalanx_2"),
("l_index_middle", "l_carpal_middle_phalanx_2"),
("l_carpal_middle_phalanx", "l_carpal_middle_phalanx_2"),
("l_index_distal", "l_carpal_distal_phalanx_2"),
("l_carpal_distal_phalanx", "l_carpal_distal_phalanx_2"),
("l_capitate", "l_capitate"),
("l_middle_metacarpal", "l_metacarpal_3"),
("l_middle_proximal", "l_carpal_proximal_phalanx_3"),
("l_middle_middle", "l_carpal_middle_phalanx_3"),
("l_middle_distal", "l_carpal_distal_phalanx_3"),
("l_hamate", "l_hamate"),
("l_ring_metacarpal", "l_metacarpal_4"),
("l_ring_proximal", "l_carpal_proximal_phalanx_4"),
("l_ring_middle", "l_carpal_middle_phalanx_4"),
("l_ring_distal", "l_carpal_distal_phalanx_4"),
("l_pinky_metacarpal", "l_metacarpal_5"),
("l_pinky_proximal", "l_carpal_proximal_phalanx_5"),
("l_pinky_middle", "l_carpal_middle_phalanx_5"),
("l_pinky_distal", "l_carpal_distal_phalanx_5"),
("r_clavicle", "r_clavicle"),
("r_scapula", "r_scapula"),
("r_upperarm", "r_upperarm"),
("r_forearm", "r_forearm"),
("r_trapezium", "r_trapezium"),
("r_thumb_metacarpal", "r_metacarpal_1"),
("r_thumb_proximal", "r_carpal_proximal_phalanx_1"),
("r_thumb_distal", "r_carpal_distal_phalanx_1"),
("r_trapezoid", "r_trapezoid"),
("r_index_metacarpal", "r_metacarpal_2"),
("r_index_proximal", "r_carpal_proximal_phalanx_2"),
("r_carpal_proximal_phalanx", "r_carpal_proximal_phalanx_2"),
("r_index_middle", "r_carpal_middle_phalanx_2"),
("r_carpal_middle_phalanx", "r_carpal_middle_phalanx_2"),
("r_index_distal", "r_carpal_distal_phalanx_2"),
("r_carpal_distal_phalanx", "r_carpal_distal_phalanx_2"),
("r_capitate", "r_capitate"),
("r_middle_metacarpal", "r_metacarpal_3"),
("r_middle_proximal", "r_carpal_proximal_phalanx_3"),
("r_middle_middle", "r_carpal_middle_phalanx_3"),
("r_middle_distal", "r_carpal_distal_phalanx_3"),
("r_hamate", "r_hamate"),
("r_ring_metacarpal", "r_metacarpal_4"),
("r_ring_proximal", "r_carpal_proximal_phalanx_4"),
("r_ring_middle", "r_carpal_middle_phalanx_4"),
("r_ring_distal", "r_carpal_distal_phalanx_4"),
("r_pinky_metacarpal", "r_metacarpal_5"),
("r_pinky_proximal", "r_carpal_proximal_phalanx_5"),
("r_pinky_middle", "r_carpal_middle_phalanx_5"),
("r_pinky_distal", "r_carpal_distal_phalanx_5"),
("l_hand", "l_carpal"),
("r_hand", "r_carpal"),
]

# Sort by V1 name length, descending
# This is CRITICAL to prevent partial replacements (e.g., "l_hip" replacing part of "l_hip_rotation" if not handled)
# Though in this specific HAnim case, v1 names are usually distinct enough that alphabetical is okay,
# but length-based is safer for general text replacement.
sorted_joint_map = sorted(joint_map_list, key=lambda x: len(x[0]), reverse=True)

# --- Generate the sed script ---
sed_script_path = "hanim_v1_to_v2_commands.sed"
with open(sed_script_path, "w") as f:
    f.write("# GNU sed script to map HAnim v1 to v2 joint names\n")
    f.write("# Generated script - review carefully before use.\n")
    f.write("# IMPORTANT: Backup your VRML files before running this.\n\n")

    for v1_name, v2_name in sorted_joint_map:
        # Escape potential regex characters in v1_name for safety, though HAnim names are usually simple.
        # For sed, basic regex special chars are ., *, [, ], ^, $
        # v1_name_sed_escaped = v1_name.replace('.', '\\.').replace('*', '\\*') # etc.

        f.write(f"# Mapping for: {v1_name} -> {v2_name}\n")
        # DEF v1_name Joint ...
        f.write(f"s/\\(DEF[ \t]*Joe_\\){v1_name}/\\1{v2_name}/g\n")
        f.write(f"s/\\(DEF[ \t]*\\){v1_name}/\\1{v2_name}/g\n")
        # USE v1_name
        f.write(f"s/\\(USE[ \t]*Joe_\\){v1_name}/\\1{v2_name}/g\n")
        # name "v1_name"
        f.write(f"s/\\(name[ \t]*\"\\){v1_name}\"/\\1{v2_name}\"/g\n")
        # ROUTE v1_name.field_out TO OtherNode.field_in
        f.write(f"s/\\(ROUTE[ \t]*\\){v1_name}\\(\\.[a-zA-Z0-9_][a-zA-Z0-9_]*[ \t][ \t]*TO[ \t][ \t]*[^.][^.]*\\.[a-zA-Z0-9_][a-zA-Z0-9_]*\\)/\\1{v2_name}\\2/g\n")
        f.write(f"s/\\(ROUTE[ \t]*\\){v1_name}\\(RotInterp\\.[a-zA-Z0-9_][a-zA-Z0-9_]*[ \t][ \t]*TO[ \t][ \t]*[^.][^.]*\\.[a-zA-Z0-9_][a-zA-Z0-9_]*\\)/\\1{v2_name}\\2/g\n")
        # ROUTE OtherNode.field_out TO v1_name.field_in
        f.write(f"s/\\(ROUTE[ \t]*[^.][^.]*\\.[a-zA-Z0-9_][a-zA-Z0-9_]*[ \t][ \t]*TO[ \t][ \t]*Joe_\\){v1_name}\\(\\.[a-zA-Z0-9_][a-zA-Z0-9_]*\\)/\\1{v2_name}\\2/g\n")
        f.write(f"s/\\(ROUTE[ \t]*[^.][^.]*\\.[a-zA-Z0-9_][a-zA-Z0-9_]*[ \t][ \t]*TO[ \t][ \t]*\\){v1_name}\\(RotInterp\\.[a-zA-Z0-9_][a-zA-Z0-9_]*\\)/\\1{v2_name}\\2/g\n")
        f.write(f"s/\\(#.*\\){v1_name}/\\1{v2_name}/g\n")
        f.write("\n")

print(f"Generated sed commands in: {sed_script_path}")
print("Please review this file carefully.")
print("You can then use it with GNU sed: sed -f hanim_v1_to_v2_commands.sed your_input.wrl > your_output.wrl")
